# Generated by Django 2.2.10 on 2020-04-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealorganizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mealorganizer.IngredientGroup'),
        ),
    ]
