# Generated by Django 2.2.6 on 2020-04-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealOrganizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fats', models.DecimalField(decimal_places=1, max_digits=3)),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='IngredientWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_grams', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MealOrganizer.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MealOrganizer.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='MealOrganizer.IngredientWeight', to='MealOrganizer.Ingredient'),
        ),
    ]
