# Generated by Django 2.2.10 on 2020-04-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealorganizer', '0003_recipe_preparation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientweight',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealorganizer.Recipe'),
        ),
    ]
